### ISSUE TITLE
CPU 100% with the pool

### ISSUE THREAD

**Issue by Nicolab** [ysbaddaden/earl#4]
Hello,

First of all, thank you for this lib, it's awesome. I've been testing it for five hours, top. 
I encountered a bug or a mistake on my part maybe. If the capacity of a pool is above 5, the CPU rises to 100% until I kill the process.

```crystal
 class Worker
    include Earl::Agent
    include Earl::Mailbox(String)

    def call
      while message = receive?
        p message
      end
    end

    def terminate
      puts "terminate"
    end
  end

  pool = Earl::Pool(Worker, String).new(capacity: 10)

  spawn do
    8.times do |i|
      pool.send("message #{i}")
    end
    pool.stop
    puts "stop"
  end

  pool.start
```

Is it related to the number of CPUs in my machine?

**Comment by ysbaddaden** [comment]
The culprit is `Earl::Logger`'s agent. It's mailbox becomes full and the channel then blocks whenever an agent tries to log something, which happens with `Earl::Pool` sending :info log messages.

Injecting `Earl::Logger.level = :silent` (or `:warn`) or `Earl.application.spawn` somewhere will workaround the issue. Note that it's recommended to supervise all your program agents with `Earl.application` and eventually block the main fiber with `Earl.application.start`.

**Comment by Nicolab** [comment]
Ok thanks, `Earl.application.spawn` solves the issue. I relied on the README that doesn't mention `Earl.application`. 
However, I just saw that it is specified in the source code. I'm going through the code and the specs to better understand Earl's behavior. But I don't see how he solves this problem, by restarting the logger (or mailbox) when it crashes?

> I'm in a hurry to use Earl in concrete cases, really fun (à la Elixir processes) and powerful :rocket:

**Comment by ysbaddaden** [comment]
Look at the [SPEC](https://github.com/ysbaddaden/earl/blob/master/SPEC.md) instead as well as the crystal docs, which you can access with:
```console
$ cd lib/earl
$ crystal docs
$ firefox docs/index.html
```

Basically `Earl.application` is an `Earl::Supervisor` with a few niceties: run & supervise `Earl::Logger` and any `Earl::Agent` you tell it to monitor, and also trap a few signals to exit gracefully (to some extent).

**Comment by Nicolab** [comment]
Ok thanks
